apiVersion: apps/v1
kind: Deployment
metadata:
  name: json-validator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: json-validator
  template:
    metadata:
      labels:
        app: json-validator
    spec:
      containers:
        - name: json-validator
          image: ewhatley/json-validator:v0.0.1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: json-validator
  labels:
    app: json-validator
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30080
  selector:
    app: json-validator

